# for prod

# FROM node:18
# WORKDIR /app
# COPY package.json ./
# RUN npm install
# COPY . .
# EXPOSE 9000
# CMD ["npm", "run", "dev"]

# for dev
FROM node:18
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
EXPOSE 9000
CMD ["npx", "nodemon", "app.js"]
